### ISSUE TITLE
The -p option (progressive) with jpg input files results in error and no image being put out, even when it is just on its own without any other options.

### ISSUE THREAD

**Issue by StacktraceException** [libjxl/libjxl#2563] opened 2023-06-13 15:43 UTC
**Describe the bug**
The -p option (progressive) with jpg input files results in error and no image being put out, even when it is just on its own without any other options. But when input files are png images, then this option works fine. 
**To Reproduce**
run command: .\cjxl.exe ..\..\..\Pictures\BingImageOfTheDay_20210523.jpg .\result5.jxl -p

**Expected behavior**
Image is put out properly.

**Screenshots**
this is the test image that i used: ![BingImageOfTheDay_20210523](https://github.com/libjxl/libjxl/assets/61169664/98f00afc-0ea6-4bab-9de1-d12a5a0c40a7)

**Environment**
 - OS: Windows 11 with all latest updates.
 - Compiler version: [e.g. clang 11.0.1]  This software was downloaded as an x64 binary from the releases of this github repo. I did not compile it.
 - CPU type: amd ryzen 5900hs x64 CPU.
 - cjxl/djxl version string: JPEG XL encoder v0.8.1 c27d499 [AVX2,SSE4,SSSE3,Unknown]
**Additional context**

.\cjxl.exe .\BingImageOfTheDay_20210523.jpg .\result5.jxl -p -v

The output (error?) message:
JPEG XL encoder v0.8.1 c27d499 [AVX2,SSE4,SSSE3,Unknown]
Note: Implicit-default for JPEG is lossless-transcoding. To silence this message, set --lossless_jpeg=(1|0).
Read JPEG image with 345077 bytes.
Encoding [Container | JPEG, lossless transcode, effort: 7 | JPEG reconstruction data],
D:\a\libjxl\libjxl\lib\jxl\enc_frame.cc:908: JXL_CHECK: enc_state_->passes. Size() == 1

Maybe related to the problem: there is no D: drive mounted on my pc, and the error still occurs even when the jpg is in the same dir as the cjxl.exe executable.

Kind regards.

**Comment by jonnyawsom3** [comment] 2023-06-14 22:47
Just for some info, the failed progressive on the jpeg is due to it trying to losslessly transcode it, which uses different techniques than normal and likely is what's breaking it.

The png getting massive and taking longer is because the jpeg transcode is almost instant and skips a lot of steps that normal encoding needs. If you try to compress it with only `-d 0 -p` then it should be smaller than the png at least, a lot of those options are redundant or for jpeg only.

If you want to progressively encode the jpegs before it's fixed, then try `-p -d 0 -j 0`  for lossless or `-p -d 1 -j 0` for lossy, bear in mind the results will probably be worse than the transcode.

Best for the experts to chime in, but hopefully this explains and helps somewhat

**Comment by jonsneyers** [comment] 2023-06-23 10:17
This should be fixed with https://github.com/libjxl/libjxl/pull/2479

Feel free to reopen if the issue is still there.

**Closed by jonsneyers** 2023-06-23 10:17 UTC
