### ISSUE TITLE
Crash when trying to compress

### ISSUE THREAD

**Issue by megapro17** [libjxl/libjxl#1426] opened 2022-05-17 19:47 UTC
**Describe the bug**
Cjxl just crashes without errors when trying to compress any photo. Tried on two different pc's. The same crash with ffmpeg libjxl encoder. It shows return code -1073741819. Lossless compression is working.

0.6.1 version works perfectly fine.

**To Reproduce**
`cjxl 1.jpg -q 99`

**Screenshots**
![image](https://user-images.githubusercontent.com/16743370/168896419-d5264364-865c-4828-b36d-c47074d0d429.png)

**Environment**
 - OS: Windows 11 Pro
 - Compiler version: ?
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.7.0 a444260 [AVX2,SSE4,SSSE3,Scalar]

**Additional context**
Build from https://artifacts.lucaversari.it/libjxl/libjxl/latest/

**Comment by veluca93** [comment] 2022-05-17 19:49
For future reference, `-1073741819` is the equivalent of a segmentation fault.

**Comment by veluca93** [comment] 2022-05-17 21:31
Possibly a dupe of https://github.com/libjxl/libjxl/issues/1282

**Comment by jonsneyers** [comment] 2022-05-18 08:39
What does the output of 0.6.1 look like?
Does you cpu actually support AVX2?

**Comment by megapro17** [comment] 2022-05-18 11:40
> Possibly a dupe of #1282

effort 1-4 is working for me too



> What does the output of 0.6.1 look like?

![image](https://user-images.githubusercontent.com/16743370/169030450-78fb8de1-9de2-440c-9aa4-8ddd7569d5e6.png)



> Does you cpu actually support AVX2?

Yes, i5-6500

**Comment by jonsneyers** [comment] 2022-05-18 12:32
So one thing we start doing at -e 5 is gaborish. Could you check what happens if you encode with `-e 5 --gaborish=0` ?

**Comment by megapro17** [comment] 2022-05-18 12:51
It's working
```
megapro17@megapro17-pc  R:\  cjxl 1.jpg -q 99 -e 7 --gaborish=0 -v
JPEG XL encoder v0.7.0 a444260 [AVX2,SSE4,SSSE3,Scalar]
No output file specified.
Encoding will be performed, but the result will be discarded.
Read 2550x3510 image, 74.5 MP/s
Encoding [VarDCT, d0.190, squirrel], 4 threads.
Compressed to 942806 bytes (0.843 bpp).
2550 x 3510, 3.13 MP/s [3.13, 3.13], 1 reps, 4 threads.
Average butteraugli iters:       0.00
Total layer bits headers          0.001445%       109
Total layer bits TOC              0.031213%      2354
Total layer bits quantizer        0.000265%        20
Total layer bits quant tables     0.000027%         2
Total layer bits order            0.016482%      1243   [c/i:  2.00 | hst:       8 | ex:      44 | h+c+e:     183.357]
Total layer bits DC               8.380682%    632045
Total layer bits ControlFields    5.115817%    385819
Total layer bits AC               0.413913%     31216   [c/i:128.00 | hst:    3878 | ex:       0 | h+c+e:  804709.595]
Total layer bits ACTokens        85.972705%   6483794
Total layer bits modularGlobal    0.053648%      4046   [c/i: 31.00 | hst:     505 | ex:       0 | h+c+e:  117730.411]
Total layer bits modularTree      0.013803%      1041   [c/i:  2.00 | hst:      33 | ex:      22 | h+c+e:     126.092]
Total image size              7541689   [c/i:163.00 | hst:    4426 | ex:   18305 | h+c+e:  940988.081]
Allocations: 638 (max bytes in use: 3.612251E+08)
```

**Comment by veluca93** [comment] 2022-05-20 15:20
Does this build work for you? https://github.com/sboukortt/libjxl/releases/download/windebug-2019/jxl-x64-windows-static.zip

**Comment by megapro17** [comment] 2022-05-20 15:41
Yes, no issues
```
 megapro17@megapro17-pc  R:\  cjxl 1.ppm -q 99 -e 7
JPEG XL encoder v0.7.0 7365be7 [AVX2,SSE4,SSSE3,Scalar]
No output file specified.
Encoding will be performed, but the result will be discarded.
Read 3672x2448 image, 150.9 MP/s
Encoding [VarDCT, d0.190, squirrel], 4 threads.
Compressed to 3690292 bytes (3.284 bpp).
3672 x 2448, 2.92 MP/s [2.92, 2.92], 1 reps, 4 threads.
 megapro17@megapro17-pc  R:\  cjxl 2.ppm -q 99 -e 6
JPEG XL encoder v0.7.0 7365be7 [AVX2,SSE4,SSSE3,Scalar]
No output file specified.
Encoding will be performed, but the result will be discarded.
Read 2550x3510 image, 151.3 MP/s
Encoding [VarDCT, d0.190, wombat], 4 threads.
Compressed to 900828 bytes (0.805 bpp).
2550 x 3510, 9.09 MP/s [9.09, 9.09], 1 reps, 4 threads.
 megapro17@megapro17-pc  R:\  cjxl 3.ppm -q 99 -e 1
JPEG XL encoder v0.7.0 7365be7 [AVX2,SSE4,SSSE3,Scalar]
No output file specified.
Encoding will be performed, but the result will be discarded.
Read 2560x1440 image, 115.6 MP/s
Encoding [VarDCT, d0.190, lightning], 4 threads.
Compressed to 1086774 bytes (2.358 bpp).
2560 x 1440, 30.66 MP/s [30.66, 30.66], 1 reps, 4 threads.
 megapro17@megapro17-pc  R:\  cjxl 4.ppm -q 99 -e 3 --gaborish=1
JPEG XL encoder v0.7.0 7365be7 [AVX2,SSE4,SSSE3,Scalar]
No output file specified.
Encoding will be performed, but the result will be discarded.
Read 2480x3508 image, 144.3 MP/s
Encoding [VarDCT, d0.190, falcon], 4 threads.
Compressed to 528915 bytes (0.486 bpp).
2480 x 3508, 36.41 MP/s [36.41, 36.41], 1 reps, 4 threads.
 megapro17@megapro17-pc  R:\ 
 ```

**Comment by veluca93** [comment] 2022-05-20 15:43
What's exactly your Windows version? (searching for "winver" in the start menu should tell you that)

**Comment by megapro17** [comment] 2022-05-20 15:50
21H2 22000.675

**Comment by veluca93** [comment] 2022-05-23 20:35
Newest builds should work now, please reopen if you still have issues!

**Closed by veluca93** 2022-05-23 20:35 UTC

**Comment by megapro17** [comment] 2022-05-23 20:41
Finally, big thanks for resolving this issue!
