### ISSUE TITLE
`djxl` cannot decode multi-frame output produced by the API

### ISSUE THREAD

**Issue by xiota** [libjxl/libjxl#508] opened 2021-08-28 16:55 UTC
**Describe the bug**

When `JxlEncoderAddImageFrame` is called multiple times, the resulting JXL file cannot be decoded by `djxl`.

    ../lib/jxl/dec_file.cc:172: JXL_FAILURE: DecodeFile reader position not at EOF.

When decoded with the API, only one frame is decoded.

**To Reproduce**

* Modify the `encode_oneshot` example to send the same buffer contents to the encoder multiple times.
* Or use the attached JXL file: [multi-frame-non-animation-01.zip](https://github.com/libjxl/libjxl/files/7129725/multi-frame-non-animation-01.zip)
* Attempt to decode the file with `djxl`.

**Expected behavior**

Both the API and `djxl` should be able to extract all frames.

**Environment**
 - OS: Ubuntu 21.04; Linux 5.11.—
 - Compiler version: Ubuntu clang version 12.0.0-3ubuntu1~21.04.1
 - CPU type: x86_64
 - cjxl/djxl version string: cjxl v0.6.0 84f0807 [AVX2,SSE4,Scalar]

**Additional context**

* `encode_oneshot` omits the required call to `JxlEncoderCloseInput`.  Adding it in is not sufficient to correct the problem.
* In `encode.cc`, frames are sent to the encoder with empty FrameInfo.  #509 addresses this, but it would still be prudent for `djxl` to be able to decode frames from such files.
* Setting `metadata.m.have_animation = true` without setting `frame.duration` allows `djxl` to extract the frames, but the API decodes only one frame.  Further setting `frame.duration` allows the API to decode all frames.
* This may be a duplicate of #275.  (Didn't notice before.)

**Comment by jonsneyers** [comment] 2021-11-21 14:49
I think here the issue was that the (immature) encode api was producing a jxl where every frame was marked as being the last one, so the decoder correctly complained after decoding the first frame when there was still data left.

Closing as it is a duplicate of #275

**Closed by jonsneyers** 2021-11-21 14:49 UTC
Labels: duplicate, encoder, api
