### ISSUE TITLE
Default command (effort 7) does not work in cjxl

### ISSUE THREAD

**Issue by MartinEesmaa** [libjxl/libjxl#1356] opened 2022-04-19 06:12 UTC
**Describe the bug**
Bug of encoding from any image file to jxl in cjxl for default command (7)

**To Reproduce**
1: Used code default in Windows Terminal Command Prompt: cjxl fefefe.png fefefe.jxl
2: Nothing compressed.

**Expected behavior**
Expected needs to be compressed and saved file after default command and effort number seven.

**Code:**
```
cjxl fefefe.png fefefe.jxl
JPEG XL encoder v0.7.0 75a039a [AVX2,SSE4,SSSE3,Scalar]
Read 1353x852 image, 48.0 MP/s
Encoding [VarDCT, d1.000, squirrel], 16 threads.
```

**Environment**
 - OS: Windows 11
 - Compiler version: VCPKG 2022
 - CPU type: x86_64
 - JPEG XL encoder v0.7.0 75a039a [AVX2,SSE4,SSSE3,Scalar]

**Additional context**
The problem is that the default effort does not work. From effort 1 to 4 are working well. Since effort 5, it won't work well.

- Martin Eesmaa

**Comment by jonsneyers** [comment] 2022-04-19 06:37
This is a duplicate of https://github.com/libjxl/libjxl/issues/1282

We suspect it is caused by a compiler bug.

**Comment by jonsneyers** [comment] 2022-04-19 06:37
Closing, discussion can proceed in https://github.com/libjxl/libjxl/issues/1282

**Closed by jonsneyers** 2022-04-19 06:37 UTC
