### ISSUE TITLE
Attempt to compress png wit cjxl results in error "Illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by Aerocatia** [libjxl/libjxl#3353] opened 2024-03-02 06:07 UTC
**Describe the bug**
When testing a set of a few thousand images, this ones fails to be converted by cjxl.
it does not seem to be an issue with the PNG file itself, as re-saving it with different programs or running it through `oxipng` does not change the outcome.

**To Reproduce**
Obtain the image file [1337453268931244032_1.zip](https://github.com/libjxl/libjxl/files/14468228/1337453268931244032_1.zip)
Attempt to compress it with cjxl, neither lossless or lossy work.

**Expected behavior**
A JPEG-XL file of the image is created.

**Environment**
 - OS: Linux
 - Compiler version: gcc version 13.2.1 20230801 (GCC)
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.10.1 5f67ebce [AVX2,SSE4,SSE2]

**Comment by Traneptora** [comment] 2024-03-04 04:29
I can reproduce this with the sample provided. Here's my valgrind log:

[valgrind.log](https://github.com/libjxl/libjxl/files/14476488/valgrind.log)

This was with JPEG XL encoder v0.10.0 6d041617 [AVX2].

(For some reason it says 0.10.0, even though it's the latest commit from git main.)

**Comment by Traneptora** [comment] 2024-03-04 04:30
I could reproduce this in any combination of `-d` and `-e` I tried except `-d 0 -e 1` because I assume fast lossless has a different code path.

**Comment by Traneptora** [comment] 2024-03-04 04:31
I can also reproduce this with library users (e.g. ffmpeg), it's not just stock cjxl.

**Comment by veluca93** [comment] 2024-03-04 13:46
Should be fixed in https://github.com/libjxl/libjxl/pull/3361.

**Comment by szabadka** [comment] 2024-03-04 14:22
Fix was merged.

**Closed by szabadka** 2024-03-04 14:22 UTC
Labels: bug, cjxl, v1.0
