### ISSUE TITLE
djxl : decode GIF from JXL

### ISSUE THREAD

**Issue by adil-benameur** [libjxl/libjxl#258] opened 2021-07-01 00:14 UTC
**Is your feature request related to a problem? Please describe.**
I would like to store a collection of GIFs in JXLs (because of the excellent compression). However, I would also like to restore these JXLs to their original format, GIF. I noticed that djxl can produce a series of JPEGs and PNGs from a GIF encoded to JXL. However, it can't recreate a GIF directly.

**Describe the solution you'd like**
I would like djxl to be able to decode a JXL file into a GIF file.

**Describe alternatives you've considered**
Currently, my only way to recreate a GIF from a JXL file is to transform a series of PNGs produced by dxl into a GIF.

**Report of bug ?**
When decompressing JXL to a series of JPEGs, the JPEGs produced are highly deteriorated compared to the initial quality of the GIF (even when using the options `-q 100 --pixels_to_jpeg`).

![tenor-00](https://user-images.githubusercontent.com/29207572/124045277-9854f000-da0f-11eb-91c4-0da523162075.jpg)

**Additional context**
I took this GIF file for testing : [tenor.com/bftQl.gif](https://tenor.com/bftQl.gif)

![tenor](https://user-images.githubusercontent.com/29207572/124044454-ba4d7300-da0d-11eb-9426-21f9077eff47.gif)

The version of my encoder / decoder is v0.3.7.
I'm on macOS, and use the version of jpeg-xl shipped with brew.

**Comment by jonsneyers** [comment] 2021-07-01 07:30
Looks like somehow in the case of animation, the output jpeg quality is set to 0 or something like that.

I personally don't think decoding to gif is in the scope of djxl, because in the general case (when the input was not a gif), that means djxl needs to do a color reduction, which is not at all easy to do properly (and doing it non-properly is not very useful).

Decoding to apng would be useful though, imo. You can then use existing tools from there.

**Comment by TheHardew** [comment] 2021-07-01 08:23
Btw, when I try to decode animated jxl to jpg, whether it be created on my system or from https://github.com/libjxl/conformance it just throws the error that I need to specify quality.


```
~/P/test $ djxl -q 100 1.jxl 1.jpg
JPEG XL decoder v0.3.7 [AVX2]
Read 1955913 compressed bytes.
Decoded to pixels.
build/libjxl-git/src/libjxl/lib/extras/codec_jpg.cc:481: JXL_FAILURE: please specify a 0-100 JPEG quality
Failed to write decoded image for frame 1/18.
build/libjxl-git/src/libjxl/lib/extras/codec_jpg.cc:481: JXL_FAILURE: please specify a 0-100 JPEG quality
Failed to write decoded image for frame 2/18.
[...]
build/libjxl-git/src/libjxl/lib/extras/codec_jpg.cc:481: JXL_FAILURE: please specify a 0-100 JPEG quality
Failed to write decoded image for frame 17/18.
build/libjxl-git/src/libjxl/lib/extras/codec_jpg.cc:481: JXL_FAILURE: please specify a 0-100 JPEG quality
Failed to write decoded image for frame 18/18.
498 x 498, 0.51 MP/s [0.51, 0.51], 1 reps, 4 threads.
Allocations: 2123 (max bytes in use: 7.957910E+07)
```
libjxl version f8790509f3588413413682b611cf11f18f4498b1
I think it might be related?

**Comment by mo271** [comment] 2022-03-30 12:54
Contrary to decoding to apng, where decoding from jxl already works, because of the limitations of the gif format, decoding from animated jxl to gif is out of scope.
Keeping the bug open to keep track of the JPEG issue.

**Comment by mo271** [comment] 2022-03-30 18:43
I tried to reproduce the issue when taking the animated gif from the original post and then encoding to jxl with cjxl (and also cjxl_ng). When trying to decode this animated jxl to different formats this happens:
 - png: works as intended, gives animated png
 - jpg: fails with `JXL_FAILURE: alpha is not supported`
 - gif: fails with `JXL_FAILURE: Encoding to GIF is not implemented`
So I can't seem to be getting the artifacts you describe above at the current main. If you still can reproduce the problem at the current main, please reopen.

**Comment by mo271** [comment] 2022-03-30 20:43
I can repro this with an animated jxl without alpha and also have a fix coming soon.

**Closed** 2022-03-30 21:00 UTC
Labels: enhancement, djxl
