### ISSUE TITLE
Support operating on stdin and stdout in cjxl/djxl

### ISSUE THREAD

**Issue by Fraetor** [libjxl/libjxl#542] opened 2021-09-05 22:33 UTC
**Is your feature request related to a problem? Please describe.**
For command line programs on *nix systems a common method of use is through redirecting the input and output of programs from/into other programs or files. This is done by redirecting standard input and standard output, and is a common way of doing multiple processing steps without having to write a bunch of temporary files. One of the many benefits of this is that it handles streaming data for situations when storage of the intermediate files (which are often in fully uncompressed formats) exceeds the storage of the host.

Currently cjxl and djxl only support reading and writing to files, which means that they cannot (easily) be integrated into this kind of workflow, and miss out in the described benefits.

**Describe the solution you'd like**
There are several ways this could be implemented.
Some programs, such as `cjpeg` will automatically use stdin/stdout if no files are specified as arguments.
```sh
cjpeg -quality 60 <input.ppm >output.jpg
```
Other programs have an option that will cause them to read stdin or stdout.
```sh
cjxl --stdin output.jxl < input.png
cjxl --stdout input.png > output.jxl
cjxl --stdin --stdout < input.png  > output.jxl
```
Another common pattern is using `-` in place of the filename as an alias of stdin and stdout, but I can't remember how that works.

Something that needs to be considered is that cjxl and djxl currently have output to stdout, in the encode/decode status. When using stdin/stdout this output would have to be suppressed.

I think my preferred option would be the second one, because it makes things explicit, and avoids any potential issues around not being able to operate on files called `-`, but others may have better ideas as to how this should be implemented.

**Describe alternatives you've considered**
Currently it is possible through virtual files that are aliases of stdin and stdout, as below, but this is clunky.
```sh
cjxl /dev/stdin /dev/stdout <input.png >output.jxl
```

**Additional context**
Requested by [Sedna#4917 on the JXL discord](https://discord.com/channels/794206087879852103/803663417881395200/883852155952439316).

**Comment by TheHardew** [comment] 2021-09-05 23:24
> Something that needs to be considered is that cjxl and djxl currently have output to stdout, in the encode/decode status. When using stdin/stdout this output would have to be suppressed.

most of those messages are on stderr. When `djxl` prints the number of allocations, that is on stdout so I guess that needs to be fixed and maybe there are some other rare situations?

**Comment by jloqfjgk** [comment] 2021-09-08 01:14
Related / Duplicate of:
* [Support for piping from other commandline tools like imagemagick. (Open)](https://gitlab.com/wg1/jpeg-xl/-/issues/38)
* [Support standard input/output streams (Closed)](https://gitlab.com/wg1/jpeg-xl/-/issues/242)

**Comment by jonsneyers** [comment] 2021-09-10 14:48
It should work now for `cjxl`, and also input to `djxl` should work. Output from `djxl` is trickier, maybe if we add APNG output support (currently we don't have it) we could output that when writing to stdout. It has to be a format that supports animation because writing possibly multiple files (one for each frame) to stdout isn't going to be useful.

Alternatively, is there some uncompressed multi-frame format that we could use? (what tools would you want to pipe djxl output to, and what formats can they handle?)

**Comment by TheHardew** [comment] 2021-09-10 15:26
I think in Y'CbCr you can use yuv4mpeg. It could be usefull e.g. when decoding an animation consisting of jpeg frames (e.g. compressed mjpeg files, I think it should be possible with `JxlEncoderAddJPEGFrame()`?). No idea about RGB though. I don't think even ffmpeg has such an option, sadly.

**Comment by adamburgess** [comment] 2021-09-10 15:33
ffmpeg supports a couple:
* [rawvideo](https://ffmpeg.org/ffmpeg-formats.html#rawvideo) demuxer can read raw frames in most pixel formats from stdin
* [image2pipe](https://ffmpeg.org/ffmpeg-formats.html#image2-1) demuxer can read multiple frames of any image format that ffmpeg supports from stdin
* [apng](https://ffmpeg.org/ffmpeg-formats.html#apng) demuxer can read apng

**Comment by jonsneyers** [comment] 2021-09-10 15:36
We don't currently have an option to skip YCbCr->RGB in the decoder and return YCbCr output - it might be useful to add that, but then if the image is not using YCbCr (but XYB or RGB), we also need to implement RGB->YCbCr.

Maybe we should add MIFF as an output format. https://www.imagemagick.org/script/miff.php

**Comment by jonsneyers** [comment] 2021-09-10 15:37
> ffmpeg supports a couple:
> 
> * [rawvideo](https://ffmpeg.org/ffmpeg-formats.html#rawvideo) demuxer can read raw frames in most pixel formats from stdin
> * [image2pipe](https://ffmpeg.org/ffmpeg-formats.html#image2-1) demuxer can read multiple frames of any image format that ffmpeg supports from stdin
> * [apng](https://ffmpeg.org/ffmpeg-formats.html#apng) demuxer can read apng

for the first two, how does it know dimensions and timing?

**Comment by adamburgess** [comment] 2021-09-10 15:39
For rawvideo, `Since there is no header specifying the assumed video parameters, the user must specify them in order to be able to decode the data correctly.`
For images2pipe, it takes the dimensions from the first image, and framerate must be specified manually, 25 as default

**Comment by thebombzen** [comment] 2021-09-10 19:37
Also worth mentioning that strictly speaking FFmpeg supports variable size as a whole, in the same way it supports variable framerate
but many things expect constant size and will error or produce nonsense otherwise

**Comment by thebombzen** [comment] 2021-09-10 19:46
> We don't currently have an option to skip YCbCr->RGB in the decoder and return YCbCr output - it might be useful to add that, but then if the image is not using YCbCr (but XYB or RGB), we also need to implement RGB->YCbCr.
There shouldn't really be any reason this has to be done. If the image is using YCbCr, then adding the option of leaving it that way or converting to RGB makes sense, although the caveat is one of Matrix. Does JpegXL use the BT.709 matrix or is it configurable? That's the kind of information that should be available to API callers that request YCbCr anyway, or documented if it's always the same one.

If the image is RGB then just continue to only return RGB in the decoder and refuse if YCbCr is requested, saying "image is RGB."

> Maybe we should add MIFF as an output format. https://www.imagemagick.org/script/miff.php

**Comment by jonsneyers** [comment] 2021-09-10 20:04
The only kind of YCbCr we support, is the one that is used in jpeg/jfif: full range YCbCr, not tv range, interstitial chroma samples in case of subsampling, not cosited. The only reason we support YCbCr is to do jpeg recompression (though you could also use it to do lossless y4m compression, except it will always interpret it as full range and interstitial).

**Comment by LeviPesin** [comment] 2021-09-25 04:25
For some reason this does not work in Windows. I tested it with `type test.ppm > cjxl - - > test.jxl`, and it prints `The system cannot find the file specified. Error occured while processing: -.` twice.

**Comment by LeviPesin** [comment] 2021-09-25 07:09
It works with file instead of stdin, i.e. `cjxl test.ppm - > test.jxl`, but both `type test.ppm > cjxl - test.jxl` and `type test.ppm > cjxl - - > test.jxl` don't.

**Comment by TheHardew** [comment] 2021-09-25 07:59
@LeviPesin try `type test.ppm | cjxl - - > test.jxl`?

**Comment by LeviPesin** [comment] 2021-09-25 12:04
Then it outputs `Failed to read image -. The process tried to write to a nonexistent pipe.`.

**Comment by TheHardew** [comment] 2021-09-25 14:50
I tried it out and stdin input does seem broken. Output to stdout from `cjxl` works though. 
I tried `type 1.png | ffmpeg -i pipe: 2.png` and it does work, which is why I think the problem is with libjxl.

Just to be clear, @LeviPesin, your original code, `type test.ppm > cjxl - test.jxl` is wrong, because `>` is used to redirect stdout to a file. `|` is used to redirect it to another command. At least that's how it works on linux (`bash`, `fish`...) and it seems to be the same on winddows (batch).

**Comment by ValZapod** [comment] 2022-05-05 21:01
> The only kind of YCbCr we support, is the one that is used in jpeg/jfif: full range YCbCr,

And BT.601 matrix. BTW, Jpeg 2000 supports all kind of stuff: PhotoYCC from Kodak, 3 types of YCbCr, CMY(K), YCCK and CIELab... Also part 2 of 2000 support also later added support for CIEJab, e-sRGB, ROMM, YPbPr...

**Comment by jonsneyers** [comment] 2022-05-05 21:18
Then again, you can probably construct an icc profile for all of those...

**Comment by ValZapod** [comment] 2022-05-05 21:39
> Then again, you can probably construct an icc profile for all of those...

No, those define "matrix". For example, PhotoYCC has different quantisation, not simple 16-236, 16-240, but much more complex, CMYK has even more complex behaviour, since neither sRGB is contained in it, not vice versa, and it must have some ICC profile, since there is not default. ICC profiles operate on transfer and primaries, this defines matrix, if you wish.

**Comment by jonsneyers** [comment] 2022-05-05 22:14
I know, but icc profiles can at least approximate things quite well with lookup tables, if not represent things exactly. If you want to use a different ycbcr matrix, you could define an icc profile that includes that matrix already, and encode the image like that.

**Comment by ValZapod** [comment] 2022-05-11 13:05
> If you want to use a different ycbcr matrix, you could define an icc profile that includes that matrix already, and encode the image like that.

Matrix of ICC is not what you think it is, in ITU workflows Matrix means YCbCr or CMYK or other, but in ICC it means Matrix that goes from linear RGB to XYZ. That is primaries in ITU, the matrix depends on white point and 3 primries. https://www.color.org/hdr/02-Luke_Wallis.mp4

**Comment by wudimobile** [comment] 2022-11-28 06:56
Sorry for my poor English
Is there now a way for cjxl/djxl to use stdin/stdout on Windows?

**Comment by Traneptora** [comment] 2024-08-10 13:23
@jojje try using this patch, and see if it fixes the issue:

https://github.com/Traneptora/libjxl/commit/800cc636af4d4b69049479d4b52f33d9176e67d2

**Comment by jojje** [comment] 2024-08-10 21:18
The patch looks _logical_, but I can't verify it since I'm unable to get libjxl (cjxl specifically) to compile on windows. Either using MSVC with cmake or mingw64. 

So we'd need someone who _is_ able to build this _[rube goldberg machine](https://en.wikipedia.org/wiki/Rube_Goldberg_machine)_ on windows to confirm whether the patch fixes the issue or not.

**Comment by sboukortt** [comment] 2024-08-15 11:50
I would be curious to hear about the difficulties you have encountered trying to build `libjxl` on Windows. For me, it has worked out of the box with MinGW (through MSYS2) ever since #2987.

**Comment by AlifianK** [comment] 2024-08-22 10:48
On Windows, using @Traneptora's patch, it works.
```
➜ .\cjxl.exe img.png - | .\djxl - --disable_output
JPEG XL encoder v0.11.0 bf09101f [AVX2]
JPEG XL decoder v0.11.0 bf09101f [AVX2]
Encoding [VarDCT, d1.000, effort: 7]
Compressed to 282.5 kB (0.800 bpp).
1413 x 2000,  2.515 MP/s [2.51, 2.51], , 1 reps, 4 threads.
Decoded to pixels.
1413 x 2000,  53.549 MP/s [53.55, 53.55], , 1 reps, 4 threads.
```

Roundtrip
```
➜ .\cjxl.exe img.png - | .\djxl - --output_format png - | .\cjxl - 1.jxl
JPEG XL encoder v0.11.0 bf09101f [AVX2]
JPEG XL decoder v0.11.0 bf09101f [AVX2]
JPEG XL encoder v0.11.0 bf09101f [AVX2]
Encoding [VarDCT, d1.000, effort: 7]
Compressed to 282.5 kB (0.800 bpp).
1413 x 2000,  2.470 MP/s [2.47, 2.47], , 1 reps, 4 threads.
Decoded to pixels.
1413 x 2000,  58.531 MP/s [58.53, 58.53], , 1 reps, 4 threads.
Encoding [VarDCT, d1.000, effort: 7]
Compressed to 278.3 kB (0.788 bpp).
1413 x 2000,  2.736 MP/s [2.74, 2.74], , 1 reps, 4 threads.
```
Keep in mind that I turned on UTF-8 beta feature globally on my machine, I have no idea if it works with the Windows default UTF-16.

**Comment by jojje** [comment] 2024-08-22 16:34
Text encoding shouldn't matter. The syscall the patch makes should set the streams (file handles) in binary mode, and your test shows it does that. So @Traneptora, mind opening a PR with this patch?

**Comment by AlifianK** [comment] 2024-08-22 17:04
Already did actually, it's [#3750](https://github.com/libjxl/libjxl/pull/3750), I tested that pull request.

**Closed** 2024-08-27 15:26 UTC
Labels: cjxl, djxl, unrelated to 1.0
