### ISSUE TITLE
 Fast lossless can produce invalid/incorrect JXLs

### ISSUE THREAD

**Issue by alistair7** [libjxl/libjxl#2118] opened 2023-01-29 13:31 UTC
cjxl in fast lossless mode produces invalid JXLs from the attached PNGs.

**To Reproduce**
Encode the attached PNGs with `cjxl -e 1 -d 0` and attempt to decode.

![failure.png](https://user-images.githubusercontent.com/16582685/215329162-c94173e3-8f5e-4050-a95e-726a16ba997f.png)
[failure.png](https://user-images.githubusercontent.com/16582685/215329162-c94173e3-8f5e-4050-a95e-726a16ba997f.png)
```
$ cjxl failure.png failure.jxl -d 0 -e 1 && djxl failure.jxl --disable_output
JPEG XL encoder v0.9.0 20ca234f [AVX2,SSE4,SSSE3,Unknown]
./lib/extras/dec/color_hints.cc:54: No color_space/icc_pathname given, assuming sRGB
Read 2x2 image, 84 bytes, 0.3 MP/s
Encoding [Modular, lossless, effort: 1], 
Compressed to 183 bytes (366.000 bpp).
2 x 2, 0.00 MP/s [0.00, 0.00], 1 reps, 8 threads.
JPEG XL decoder v0.9.0 20ca234f [AVX2,SSE4,SSSE3,Unknown]
Read 183 compressed bytes.
./lib/jxl/modular/encoding/encoding.cc:566: JXL_FAILURE: Truncated input
./lib/jxl/modular/encoding/encoding.cc:597: JXL_RETURN_IF_ERROR code=1: dec_status
./lib/jxl/dec_modular.cc:257: JXL_RETURN_IF_ERROR code=1: dec_status
./lib/jxl/decode.cc:1139: frame out of bounds
Failed to decode image
DecompressJxlToPackedPixelFile failed
```

Decoder backtrace to the first failure:

```
#0  jxl::ModularDecode (br=0x5555555f4760, image=..., header=..., group_id=0, options=0x7fffffffd1e0, global_tree=0x5555555fb748, global_code=0x5555555fb760, global_ctx_map=0x5555555fb7f0, allow_truncated_group=false)
    at ./lib/jxl/modular/encoding/encoding.cc:566
#1  0x00007ffff7b5b9bd in jxl::ModularGenericDecompress (br=0x5555555f4760, image=..., header=0x5555555fb808, group_id=0, options=0x7fffffffd1e0, undo_transforms=false, tree=0x5555555fb748, code=0x5555555fb760, ctx_map=0x5555555fb7f0, allow_truncated_group=false)
    at ./lib/jxl/modular/encoding/encoding.cc:595
#2  0x00007ffff7adba31 in jxl::ModularFrameDecoder::DecodeGlobalInfo (this=0x5555555fb640, reader=0x5555555f4760, frame_header=..., allow_truncated_group=false) at ./lib/jxl/dec_modular.cc:252
#3  0x00007ffff7a4c3d0 in jxl::FrameDecoder::ProcessDCGlobal (this=0x5555555fb330, br=0x5555555f4760) at ./lib/jxl/dec_frame.cc:292
#4  0x00007ffff7a4f14e in jxl::FrameDecoder::ProcessSections (this=0x5555555fb330, sections=0x5555555fbf70, num=1, section_status=0x5555555fbf90) at ./lib/jxl/dec_frame.cc:619
#5  0x00007ffff7afa4e1 in jxl::(anonymous namespace)::JxlDecoderProcessSections (dec=0x5555555f4bd0) at ./lib/jxl/decode.cc:1123
#6  0x00007ffff7afbc1d in jxl::(anonymous namespace)::JxlDecoderProcessCodestream (dec=0x5555555f4bd0) at ./lib/jxl/decode.cc:1438
#7  0x00007ffff7afd682 in HandleBoxes (dec=0x5555555f4bd0) at ./lib/jxl/decode.cc:1898
#8  0x00007ffff7afdd42 in JxlDecoderProcessInput (dec=0x5555555f4bd0) at ./lib/jxl/decode.cc:2049
#9  0x0000555555570546 in jxl::extras::DecodeImageJXL (bytes=0x5555555f4af0 "\377\nA\300J\b\b\020", bytes_size=201, dparams=..., decoded_bytes=0x7fffffffdd40, ppf=0x7fffffffe230, jpeg_bytes=0x0) at ./lib/extras/dec/jxl.cc:205
#10 0x000055555555e7f3 in (anonymous namespace)::DecompressJxlToPackedPixelFile (args=..., compressed=std::vector of length 201, capacity 201 = {...}, accepted_formats=std::vector of length 0, capacity 0, runner=0x5555555f3ae0, ppf=0x7fffffffe230, decoded_bytes=0x7fffffffdd40, 
    stats=0x7fffffffde30) at ./tools/djxl_main.cc:283
#11 0x000055555555f378 in main (argc=3, argv=0x7fffffffe568) at ./tools/djxl_main.cc:437
```

The second PNG attached here is a crop of the first one - it appears to work correctly, but decodes to the wrong pixels.
![wrongpixels.png](https://user-images.githubusercontent.com/16582685/215329196-362ccb34-8553-45ac-92f5-4683eb492a31.png)
[wrongpixels.png](https://user-images.githubusercontent.com/16582685/215329196-362ccb34-8553-45ac-92f5-4683eb492a31.png)

```
$ cjxl wrongpixels.png wrongpixels.jxl -d 0 -e 1
JPEG XL encoder v0.9.0 20ca234f [AVX2,SSE4,SSSE3,Unknown]
./lib/extras/dec/color_hints.cc:54: No color_space/icc_pathname given, assuming sRGB
Read 1x2 image, 75 bytes, 0.1 MP/s
Encoding [Modular, lossless, effort: 1], 
Compressed to 182 bytes (728.000 bpp).
1 x 2, 0.00 MP/s [0.00, 0.00], 1 reps, 8 threads.

$ magick identify -format '%#\n' wrongpixels.png wrongpixels.jxl
3674e32a54f125bc23b069ab31af8043f8f17a02ae27f6f22ff19ffdb0961318
c31c8fa31580112a8f7f8aaca994ec1ef63511a32600dca28e2ec02aebfe6a36

$ magick identify -verbose wrongpixels.png wrongpixels.jxl  | grep Colors:
  Colors: 2
  Colors: 1
```

In this case the result is fully transparent - a slightly wider crop around the same pixels resulted in some strange artifacts, as if a section of the image had been rotated 90°.

I haven't been able to reproduce it with inputs larger than a few pixels.

**Expected behavior**
Successful encoding and decoding.

**Environment**
 - OS: Linux
 - Compiler version: clang 14.0.0
 - CPU type: x86_64
 - cjxl/djxl version string: v0.9.0 20ca234f [AVX2,SSE4,SSSE3,Unknown]

**Additional context**
The symptoms are similar to #2039 but the example PNG from that bug doesn't cause a problem now.

**Comment by mo271** [comment] 2023-01-30 08:22
Thanks for the report, this is clearly something that should be fixed...

**Comment by mo271** [comment] 2023-01-30 10:51
Bisecting this gives that d4d4c65537529c360bfd654df9c110662fba6ee2 is the first bad commit, so this seems to be a regression introduced in https://github.com/libjxl/libjxl/pull/2011/

**Closed** 2023-01-31 11:19 UTC
Labels: bug, cjxl, djxl, regression, unrelated to 1.0
