### ISSUE TITLE
Some jxl files will be decoded into two files with ec0 and ec1

### ISSUE THREAD

**Issue by dbtsai** [libjxl/libjxl#2813] opened 2023-09-21 06:07 UTC
**Describe the bug**

I'm writing a script to automate the conversions from jxl to other formats. For some jxl files, it will decode into two files with ec0 and ec1 in the filename, and the one with ec1 is empty image.  When this happens, I don't see any error message. 

**To Reproduce**
`djxl IMG_0001.jxl IMG_0001.ppm` 
will create
`IMG_0001-ec0.ppm` and `IMG_0001-ec1.pgm` without any error message. 

**Expected behavior**
Should only create one file

**Environment**
 - OS: Mac
 - CPU type: ARM
 - cjxl/djxl version string: JPEG XL decoder v0.8.2

**Comment by mo271** [comment] 2023-09-21 07:45
Thanks for the report!

The reason this is happening, is that your `IMG_0001`, probably has an alpha channel, but `ppm` does not support alpha, so what happens is that `djxl` will store the the color channels in `IMG_0001-ec0.ppm` and the alpha channel in `IMG_0001-ec1.pgm`. 
In some sense this is expected behavior, but I suppose we could do a better job at documenting this, or even change the behavior here.

Related to that, when you take you image with alpha and use `djxl` to decode it to `jpeg`,  (which of course also does not support alpha) areas with full transparency before will not necessarily be filled with white pixels in the `jpeg`. 

To reproduce
```
~/libjxl (cms_new)> wget https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png -O alpha.png
[...]

~/libjxl (cms_new)> cjxl alpha.png alpha.jxl
JPEG XL encoder v0.9.0 d87701cb [AVX2,SSE4,SSE2]
Encoding [VarDCT, d1.000, effort: 7]
Compressed to 51920 bytes (0.865 bpp).
800 x 600, 3.978 MP/s [3.98, 3.98], 1 reps, 8 threads.
~/libjxl (cms_new)> djxl alpha.jxl alpha.ppm
JPEG XL decoder v0.9.0 d87701cb [AVX2,SSE4,SSE2]
Decoded to pixels.
800 x 600, 32.547 MP/s [32.55, 32.55], 1 reps, 8 threads.
~/libjxl (cms_new)> ls alpha*
alpha-ec0.ppm  alpha-ec1.pgm  alpha.jxl  alpha.png
~/libjxl (cms_new)> djxl alpha.jxl alpha.jpeg
JPEG XL decoder v0.9.0 d87701cb [AVX2,SSE4,SSE2]
Warning: could not decode losslessly to JPEG. Retrying with --pixels_to_jpeg...
Decoded to pixels.
800 x 600, 44.971 MP/s [44.97, 44.97], 1 reps, 8 threads.
```

![alpha.png](https://github.com/libjxl/libjxl/assets/3491627/c843c239-8759-4aab-9e49-473714217b5c)
![alpha.jpeg](https://github.com/libjxl/libjxl/assets/3491627/71e604b4-ac6a-4b51-8483-585809ea1e3b)

**Comment by mo271** [comment] 2023-09-22 05:16
I hope this issue is fixed now, yielding less surprises and more control when handling images with extra channels...
Please feel free to re-open when there still is an issue.

**Closed by mo271** 2023-09-22 05:16 UTC
Labels: good first issue, djxl, unrelated to 1.0
