### ISSUE TITLE
Why does current release not have compiled packages?

### ISSUE THREAD

**Issue by jumper444** [libjxl/libjxl#2821] opened 2023-09-23 15:03 UTC
May I ask why the current 'latest' release of JXL (0.8.2; back in june) only has code but no compiled packages?
Whereas the previous versions (0.8.1, 0.8.0, etc) have DLLs and compiles for the major systems (windows, linux, etc).
As stated on the page "Always prefer to use the latest release", but without the compiles it is a hurdle for some.

https://github.com/libjxl/libjxl/releases

**Comment by jonnyawsom3** [comment] 2023-09-23 22:15
Duplicate of #2757, the issue was 'fixed' in that the package can be re-run, but it seems no one has actually done it yet

**Comment by jumper444** [comment] 2023-09-24 17:40
Sorry for the dupe. "package 0.8.2" as the other issue title didn't help me find it.

Since this has been 'fixed' will it, at least, run the for the NEXT software release v0.8.3?

**Comment by mo271** [comment] 2023-09-25 10:26
thanks for bringing this up again, should be fixed now
And yes, for any new version, the plan is to have binaries with the releases.

**Closed by mo271** 2023-09-25 10:27 UTC
