### ISSUE TITLE
At distance >= 20, v0.6.1 + kimageformats + Gwenview fail to properly render nightly's output

### ISSUE THREAD

**Issue by antermin** [libjxl/libjxl#1732] opened 2022-09-07 14:26 UTC
**Describe the bug**

When I use nightly  cjxl to encode an image at a high distance (>=20), and uses Gwenview to view the output, the output is corrupted.

**To Reproduce**

1. Encode an image with nightly cjxl: `cjxl -d 20 wollerau.png new-20.jxl`
2. View the image in Gwenview

**Expected behavior**

The image should be rendered properly without any glitch.

**Screenshots**

![gwenview](https://user-images.githubusercontent.com/103918092/188902377-2e4e5951-05a5-4f7a-ac56-537174b04461.png)

**Environment**

 - OS: Arch Linux x86_64
 - Libraries:
   - cjxl `v0.8.0 c76ec204`(nightly CI build)
   - djxl `0.6.1` (Arch package)
   - kimageformats `5.97.0` (for JXL Qt plugin)
   - Gwenview `22.08.0`
 - [Test files](https://github.com/libjxl/libjxl/files/9522224/test-files.tar.gz)

**Comment by BlueSwordM** [comment] 2022-09-08 01:30
It might be a bug with djxl 0.6.1 since I just tried manually decoding it both with djxl 0.6.1 and djxl 0.8.0 Git from 2022-09-06, and only djxl 0.6.1 returned a similar error.

I can reproduce this issue quite easily on my end as well at a system level.

**Comment by novomesk** [comment] 2022-09-08 06:24
Interesting that the problem with `new-20.jxl` manifests when getting the buffer as 8bit integers. When reading as 32bit float, whole image is displayed.

But I have another distance 20 file: 
[gimp299_plugin_crash.zip](https://github.com/libjxl/libjxl/files/9524056/gimp299_plugin_crash.zip)

It is triggering following assert in GIMP 2.99.11 (uses libjxl 0.6.1 from MSYS2):
![jxl_assert](https://user-images.githubusercontent.com/52529860/189046902-612ef526-0b1e-4fbd-aade-5f263c61f5ec.png)

In case of GIMP, there is not a big problem, because only plug-in process crashes.

But in case of KDE/Qt applications, whole application is terminated.

So we are waiting for libjxl 0.7.0 release.

**Comment by mo271** [comment] 2022-09-14 10:09
So, I guess this can be closed with the coming 0.7.0 release.

**Comment by mo271** [comment] 2022-10-10 05:42
> So, I guess this can be closed with the coming 0.7.0 release.

Closing, because this is fixed in the 0.7.0 release

**Closed by mo271** 2022-10-10 05:42 UTC
Labels: bug
