### ISSUE TITLE
djxl is producing all-black PNGs from select JXLs

### ISSUE THREAD

**Issue by chretien195** [libjxl/libjxl#2063] opened 2023-01-13 14:25 UTC
Hello,

I have book scans stored in JXL format, and I use the "djxl" command to convert them to PNG format whenever I have to manipulate them. However, I'm noticing that "djxl" is awfully unreliable. It would produce all-black PNGs from select JXLs. I am simply running:

`djxl book001.jxl book001.png`

and expecting it to work! My only relief is that the JXLs themselves aren't corrupted (I almost had a heart attack when I first noticed the problem). ImageMagick is able to convert them flawlessly:

`convert book001.jxl book001.png`

You will find attached to this post a ZIP containing:

- book001.jxl and book004.jxl - original JXLs
- book001_djxl.png and book004_djxl.png - JXLs converted to PNG format using "djxl" (they are all-black, unexpected result)
- book001_imagemagick.png and book004_imagemagick.png - JXLs converted to PNG format using ImageMagick (expected result)

[Archive.zip](https://github.com/libjxl/libjxl/files/10412287/Archive.zip)

I am using jpeg-xl: stable 0.7.0 (bottled), which is the latest version provided by Homebrew.

**Comment by jendalinda** [comment] 2023-01-13 16:02
This seems to be fixed, the developement version decodes those jxl files correctly.

**Comment by mo271** [comment] 2023-01-25 09:51
Hi, thanks for bringing this up! I have checked and good reproduce the bug at version 0.7.0, and also that it is fixed at current head. Indeed this issue was fixed by #1752.
Closing this

**Closed by mo271** 2023-01-25 09:51 UTC
