### ISSUE TITLE
when using cjxl or djxl error:"cjxl: error while loading shared libraries: libOpenEXR-3_0.so.27: cannot open shared object file: No such file or directory" happens

### ISSUE THREAD

**Issue by silverhikari** [libjxl/libjxl#204] opened 2021-06-18 08:42 UTC
**Describe the bug**
as in title when trying to run cjxl or djxl a error shows up "cjxl: error while loading shared libraries: libOpenEXR-3_0.so.27: cannot open shared object file: No such file or directory". seeing as this was a problem with openexr i have tried both the repository version of 3.0.4 and the git version from the aur. but this still happens with either version.

**To Reproduce**
1. try to run cjxl or djxl with either openexr3.0.4 or -git with any options
**Expected behavior**
cjxl or djxl should put a list of options

**Screenshots**
If applicable, add screenshots or example input/output images to help explain your problem.

**Environment**
 - OS: Manjaro
 - Compiler version: clang 12.0.0
 - CPU type: x86_64
 - cjxl/djxl version string: unable to retrieve as error stops program from running but from install is 3.7.r80-git

**Additional context**

**Comment by TheHardew** [comment] 2021-06-18 16:31
I'm guessing you have made a partial update. You updated your system, which bumped the version to `libOpenEXR-3_0.so.28.1.0`, but since libjxl was compiled with the older version it cannot now find the dynamic library. I think a recompilation will solve this.

**Comment by jo620kix** [comment] 2021-08-03 00:59
Since you are using Manjaro, you can consider using the popular [[archlinuxcn] third-party repository](https://github.com/archlinuxcn/repo), which contains `libjxl`.

**Comment by G2G2G2G** [comment] 2021-08-05 00:15
I keep getting this as well. It's being auto replaced or removed not via any updates it happens 2-7 hours after recompilation. No system reboots, no updates, in fact you can shut almost everything down and let a system sit and eventually cjxl will have the error. 
My error is slightly different: `cjxl: error while loading shared libraries: libOpenEXR-3_1.so.29:`

(Manjaro as well, tested ~ 15 times to verify over the past week)
using: https://aur.archlinux.org/packages/libjxl-git/  (OP didn't mention if they are using that)

**Comment by jo620kix** [comment] 2021-08-05 00:22
Whenever there is a new version of openexr, libjxl have to be recompiled.

When this error happens, you can `ldd /usr/bin/cjxl` and `pacman -Ql openexr`, if the library version does not match then it indicates that libjxl needs to be recompiled.

**Comment by G2G2G2G** [comment] 2021-08-05 00:24
I've tested it with my internet unplugged, a new version of openexr isn't relevant here, as I've shown

**Comment by jo620kix** [comment] 2021-08-05 00:26
Which version of openexr have you installed?

> When recompiling the 3_1 version doesn't seem to ever exist
But [openexr 3.1.1](https://archlinux.org/packages/extra/x86_64/openexr/) should provide `libOpenEXR-3_1.so.30`, are you sure your system is fully up-to-date when recompiling?

**Comment by G2G2G2G** [comment] 2021-08-05 00:42
Read my other post, all of that is already answered.

**Comment by jo620kix** [comment] 2021-08-05 00:50
>  It's being auto replaced or removed not via any updates it happens 2-7 hours after recompilation. No system reboots, no updates, in fact you can shut almost everything down and let a system sit and eventually cjxl will have the error.

> I've tested it with my internet unplugged

If you have a working version of libjxl (i.e. linked to the same version of oepnexr you are using), and you have your Internet unplugged, and you have not run any updates, then there is no way that cjxl will suddenly have the error and randomly cannot find it after a few hours.

**Comment by G2G2G2G** [comment] 2021-08-05 01:01
Cool.
He posted an issue, I reproduced it successfully. You can complain all you want but reproducing it is easy so if you want to go for it, go for it. Something in manjaro is causing the issue. As I posted cjxl is looking for a version of libopenexr that never existed on my installation of manjaro to begin with. I installed it, updated it, and reproduced his exact issue over the past week. It was very easy to do so. 
Once again: cjxl works fine, nothing changes, all the sudden it wants a different version of openexr that was never there.

**Comment by jo620kix** [comment] 2021-08-05 01:03
I deleted my other comment because apparently [archlinuxcn] lags behind (again), so until their repo is up-to-date again, I am not going to recommend it anymore.

**Comment by jo620kix** [comment] 2021-08-05 01:10
FWIW, I use Arch Linux and I can reproduce the error, **only if** openexr is updated.

Consider this:

openexr 3.0.5 and libjxl 0.3.7 are installed.
libjxl links to `/usr/lib/libOpenEXR-3_0.so.29`.
It is now in a good state.

Now Arch Linux's latest version of openexr is 3.1.1, and you run `pacman -Syu`.
Now `/usr/lib/libOpenEXR-3_0.so.29` is gone and instead you have `/usr/lib/libOpenEXR-3_1.so.30`.
But libjxl is not updated, so it still looks for `/usr/lib/libOpenEXR-3_0.so.29`.
To resolve this you have to recompile libjxl so that it looks for `libOpenEXR-3_1.so.30` instead.

**Comment by jonsneyers** [comment] 2021-11-21 13:56
So is this a libjxl issue or a manjaro issue?

**Comment by TheHardew** [comment] 2021-11-21 21:45
I think it's a manjaro issue. This package was originally written for Arch. 
Their wiki says, that "Use the AUR [Arch User Repository] at your own risk!"
Using the same package on Arch, everything works.

**Comment by G2G2G2G** [comment] 2021-11-22 05:06
It hasn't happened again since early august (on my manjaro machine, never on arch), I think it was one specific update cycle there was a bug and after that, fixed.

**Comment by jonsneyers** [comment] 2021-11-22 06:24
Closing then.

**Closed by jonsneyers** 2021-11-22 06:24 UTC
Labels: building/portability
