### ISSUE TITLE
cjxl reports no error message upon failing to read input

### ISSUE THREAD

**Issue by thebombzen** [libjxl/libjxl#1592] opened 2022-07-11 20:39 UTC
**Describe the bug**
If you pass `cjxl` a non-existent file or a file it cannot read, it won't tell you, it will just exit with failure.

**To Reproduce**
Just run `cjxl sdkjgksgj.png` or some other nonexistent file and cjxl dumps the banner and does nothing.

**Expected behavior**
`cjxl` should print some sort of informative error message of why it didn't do anything.

**Environment**
 - OS: Tested on both Linux and Windows
- JPEG XL encoder v0.7.0 0a23d683

**Log**
```
leo@gauss ~ :) $ ls -l foo.png # no read perms
---------- 2 leo leo 2517521 Jul 31  2017 foo.png
leo@gauss ~ :) $ cjxl foo.png foo.jxl
JPEG XL encoder v0.7.0 0a23d683 [AVX2]
leo@gauss ~ :( $ cjxl selkgjsdkj
JPEG XL encoder v0.7.0 0a23d683 [AVX2]
leo@gauss ~ :( $ cjxl fkdjkgj.png
JPEG XL encoder v0.7.0 0a23d683 [AVX2]
leo@gauss ~ :( $
```

**Comment by mo271** [comment] 2022-07-12 06:19
Thanks @thebombzen for reporting this! I can reproduce it at the current head, and I agree that a more useful error message would be helpful! (We already provide such an message when compiling in `opt` or `debug` mode, but also for `release` I think we shouldn't just quit silently. 

Can you check that this is working for you as intended with `cjxl_ng` after https://github.com/libjxl/libjxl/commit/87e01613f6282060b12f08a0e5a05f3960cfb710?

```
firsching@euler ~/libjxl ((ae5c655b…))> ./build/tools/cjxl_ng asdf
JPEG XL encoder v0.7.0 ae5c655b [AVX3,AVX2,SSE4,SSSE3,Emu128]
No output file specified.
Encoding will be performed, but the result will be discarded.
Reading image data failed.
firsching@euler ~/libjxl ((ae5c655b…)) [1]>
```

**Comment by mo271** [comment] 2022-07-12 06:20
I think we should make the error handling here consistent between `cjxl` and `djxl`

**Comment by thebombzen** [comment] 2022-07-12 12:57
> Can you check that this is working for you as intended with `cjxl_ng` after [87e0161](https://github.com/libjxl/libjxl/commit/87e01613f6282060b12f08a0e5a05f3960cfb710)?

It is not, as of libjxl/libjxl@6612139. 
```
leo@gauss ~/Programs/libjxl/libjxl :( $ tools/cjxl_ng ksjdgkd sgjdksfgj
JPEG XL encoder v0.7.0 6612139 [AVX2]
Setting encoder option from flag -- modular_lossy_palettefailed.
leo@gauss ~/Programs/libjxl/libjxl :( $ 
```

**Comment by mo271** [comment] 2022-07-13 12:21
> > Can you check that this is working for you as intended with `cjxl_ng` after [87e0161](https://github.com/libjxl/libjxl/commit/87e01613f6282060b12f08a0e5a05f3960cfb710)?
> 
> It is not, as of [6612139](https://github.com/libjxl/libjxl/commit/6612139).
> 
> ```
> leo@gauss ~/Programs/libjxl/libjxl :( $ tools/cjxl_ng ksjdgkd sgjdksfgj
> JPEG XL encoder v0.7.0 6612139 [AVX2]
> Setting encoder option from flag -- modular_lossy_palettefailed.
> leo@gauss ~/Programs/libjxl/libjxl :( $ 
> ```

What settings did you use here when compiling, @thebombzen? I want to repro the problem with `modular_lossy_palette` cjxl_ng and check if https://github.com/libjxl/libjxl/pull/1595 fixed the problem.

**Comment by mo271** [comment] 2022-07-13 13:42
Cool, thanks very much for trying @thebombzen! I plan to fix the initial problem with `cjxl` you describe by changing `cjxl_ng` to become `cjxl`, which is planned to happen soon. Keeping this issue open so long.

**Comment by mo271** [comment] 2022-07-18 04:54
Should be fixed by https://github.com/libjxl/libjxl/pull/1619.

**Closed by mo271** 2022-07-18 04:54 UTC
