### ISSUE TITLE
`cjxl` - lossy encoding grayscale jpeg fails

### ISSUE THREAD

**Issue by eddiezato** [libjxl/libjxl#764] opened 2021-10-22 16:41 UTC
**Describe the bug**
Can't encode the image

<img src=https://user-images.githubusercontent.com/11173476/138491058-fadbcb58-223d-4311-9212-144fc9acb42d.jpg width=200/>

**To Reproduce**
```
cjxl 0.jpg -j
JPEG XL encoder v0.7.0 0c3c093 [SSE4]
./lib/extras/packed_image_convert.cc:125: JXL_ASSERT: io->metadata.m.color_encoding.IsGray() == (frame.color.format.num_channels <= 2)
```

**Environment**
 - OS: Windows
 - Compiler version: clang 13.0.0
 - CPU type: x64
 - cjxl/djxl version string: JPEG XL encoder v0.7.0 0c3c093 [SSE4]

**Comment by jonsneyers** [comment] 2021-11-17 16:27
I think this was fixed by https://github.com/libjxl/libjxl/pull/846.
At least I cannot reproduce anymore now that that one has landed.

Please reopen if I'm wrong.

**Closed by jonsneyers** 2021-11-17 16:27 UTC
Labels: bug, cjxl

**Comment by eddiezato** [comment] 2021-11-17 16:54
Yeah, seems to have been fixed.
