### ISSUE TITLE
Wrong grayscale-16bits lossy encoding result 

### ISSUE THREAD

**Issue by sguinebert** [libjxl/libjxl#695] opened 2021-10-06 14:00 UTC
Using query.png (grayscale-16bits) - 250ko
cjxl query.png output.jxl -d 1.0 

this command give 1ko very visually lossy result (approximately 1ko)

**Comment by SylvainGui** [comment] 2021-10-06 15:38
![query](https://user-images.githubusercontent.com/41520688/136236705-34c163c4-62ae-4b46-97ae-598e50f770ca.png)

**Comment by SylvainGui** [comment] 2021-10-06 15:39
the image is not scale but present [0 - 400]

**Comment by jonsneyers** [comment] 2021-10-06 15:45
That image looks black to me. If you want to use lossy compression, you need to give the image to the encoder in the same way as how you want to view it. It's a perceptual encoder, not a black-box numbers in, lossy numbers out thing.

So make sure you scale your image properly before feeding it to the encoder. Otherwise it will just think it's an extremely dark image, and quantize information away accordingly.

**Comment by jonsneyers** [comment] 2021-10-06 15:51
When I take that png, convert it to pgm, change the pgm header to say 511 as the maximum value instead of 65535, and then run `convert foo.pgm -depth 16 new_input.png`, it creates a png that can be fed to cjxl and it will do something more sensible. (looks like pgm input in arbitrary bitdepth is currently broken in cjxl, so don't try that)

If you know the range is specifically 0-400, it would be even better to scale it so that 400 becomes the maximum value.

**Comment by jonsneyers** [comment] 2021-11-19 17:07
Closing this issue since it's a wontfix. Giving an almost-black image as input to lossy encoding will result in an almost-black output image, which is expected behavior. There being a lot of artifacts if you massively blow up the contrast in the near-blacks, is expected behavior and even desirable - the point of perceptually-optimized lossy compression is to have artifacts you cannot see, not to have no artifacts at all or to have mathematically uniform artifacts.

**Closed by jonsneyers** 2021-11-19 17:07 UTC
Labels: question, wontfix
